import './globals.css';
import { Inter } from 'next/font/google';
import React from 'react';
import { cn } from '@app/lib/utils';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={cn('bg-white', inter.className)}>{children}</body>
    </html>
  );
}
